'use strict';
const $=id=>document.getElementById(id), colors=['#0072b2','#d55e00','#009e73','#b1579d','#826b16','#6454a4','#3c8190','#a45139'];
const short=s=>s.replace('Courses with Course Subject: ',''),tip=$('tooltip');
function el(tag,text,parent,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;if(parent)parent.append(e);return e;}
function tooltip(e,text){tip.textContent=text;tip.hidden=false;tip.style.left=Math.max(8,Math.min(e.clientX+12,innerWidth-350))+'px';tip.style.top=Math.max(8,Math.min(e.clientY+12,innerHeight-tip.offsetHeight-12))+'px';}
function hideTip(){tip.hidden=true;}
fetch('../data/lab8/explorer.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json();}).then(init).catch(e=>{$('status').textContent='Unable to load Lab 8: '+e.message+'. Serve the repository with python -m http.server 8000.';$('status').className='error';});
function init(data){
const rows=data.passages,byId=new Map(rows.map(d=>[d.passage_id,d]));let selected=null,cell=null,neighbors=new Set();
$('status').textContent=`Ready · ${rows.length.toLocaleString()} passages · 8 semantic topics`;
for(const [v,t] of [[data.audit.raw_passages,'Raw passage blocks'],[rows.length,'Clean passages'],[data.audit.mean_words.toFixed(1),'Mean words / passage'],[data.sections.length,'Formal sections']]){const div=el('div',undefined,$('stats'));el('strong',v,div);el('span',t,div);}
$('scope').textContent=data.audit.scope;$('hierarchy').textContent=data.audit.hierarchy;
for(const s of [...data.sections].sort((a,b)=>b.count-a.count)){const tr=el('tr',undefined,$('section-summary'));el('td',short(s.section),tr);el('td',s.count,tr);el('td',s.mean_words,tr);}
const terms=data.top_terms.slice(0,10),tx=d3.scaleLinear().domain([0,d3.max(terms,d=>d.score)]).range([0,270]),ts=d3.select('#term-chart').append('svg').attr('viewBox','0 0 450 260').attr('role','img').attr('aria-label','Top ten terms by mean TF-IDF');
terms.forEach((d,i)=>{ts.append('text').attr('x',100).attr('y',i*25+17).attr('text-anchor','end').attr('font-size',12).text(d.term);ts.append('rect').attr('x',110).attr('y',i*25+3).attr('width',tx(d.score)).attr('height',18).attr('fill','#087e80');ts.append('text').attr('x',tx(d.score)+116).attr('y',i*25+17).attr('font-size',10).text(d.score.toFixed(3));});
data.sections.forEach(s=>{el('option',short(s.section),$('section-filter')).value=s.section;});
data.topics.forEach(t=>{el('option',t.name,$('topic-filter')).value=t.id;const k=el('span',undefined,$('topic-legend'),'key'),sw=el('span',undefined,k,'swatch');sw.style.background=colors[t.id];el('span',`${t.id+1}. ${t.name} (${t.count})`,k);});
const W=620,H=500,x=d3.scaleLinear().domain(d3.extent(rows,d=>d.x)).nice().range([25,W-25]),y=d3.scaleLinear().domain(d3.extent(rows,d=>d.y)).nice().range([H-25,25]),radius=d3.scaleSqrt().domain([0,d3.max(rows,d=>d.word_count)]).range([0,7]);
const sz=d3.select('#size-legend').append('svg').attr('width',330).attr('height',43);[25,100,200].forEach((n,i)=>{sz.append('circle').attr('cx',15+i*105).attr('cy',18).attr('r',radius(n)).attr('fill','#647c75');sz.append('text').attr('x',28+i*105).attr('y',22).attr('font-size',11).text(n+' words');});
const svg=d3.select('#map').append('svg').attr('viewBox',`0 0 ${W} ${H}`).attr('aria-label','Semantic passage map');svg.append('defs').append('clipPath').attr('id','clip').append('rect').attr('width',W).attr('height',H);const layer=svg.append('g').attr('clip-path','url(#clip)').append('g');
const points=layer.selectAll('circle').data(rows).join('circle').attr('class','passage').attr('cx',d=>x(d.x)).attr('cy',d=>y(d.y)).attr('r',d=>radius(d.word_count)).attr('fill',d=>colors[d.cluster]).attr('tabindex',0).attr('role','button').attr('aria-label',d=>`${d.passage_id}, ${d.cluster_name}, ${short(d.section)}, page ${d.page}`).on('click',(_,d)=>select(d)).on('keydown',(e,d)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(d);}}).on('mousemove',(e,d)=>tooltip(e,`${d.cluster_name} · p. ${d.page}\n${short(d.section)}\n${d.text.slice(0,180)}…`)).on('mouseleave',hideTip);
const zoom=d3.zoom().scaleExtent([.6,12]).on('zoom',e=>{layer.attr('transform',e.transform);points.attr('r',d=>radius(d.word_count)/Math.sqrt(e.transform.k));});svg.call(zoom);$('zoom-in').onclick=()=>svg.transition().duration(200).call(zoom.scaleBy,1.5);$('zoom-out').onclick=()=>svg.transition().duration(200).call(zoom.scaleBy,1/1.5);$('zoom-reset').onclick=()=>svg.transition().duration(200).call(zoom.transform,d3.zoomIdentity);
const max=d3.max(data.matrix,d=>d.count),heat=d3.scaleSequential(d3.interpolateBuGn).domain([0,max]);el('span','Passages: 0 ',$('matrix-legend'));el('span',undefined,$('matrix-legend')).style.cssText='display:inline-block;width:110px;height:10px;background:linear-gradient(to right,#f7fcfd,#00441b);margin:0 8px';el('span',max,$('matrix-legend'));
const head=el('tr',undefined,$('matrix').querySelector('thead'));el('th','Formal section',head);data.topics.forEach(t=>{const th=el('th',t.id+1,head);th.title=t.name;th.style.color=colors[t.id];th.scope='col';});
const cells=[],lookup=new Map(data.matrix.map(d=>[d.section+'|'+d.cluster,d]));data.sections.forEach(s=>{const tr=el('tr',undefined,$('matrix').querySelector('tbody'));el('th',short(s.section),tr).scope='row';data.topics.forEach(t=>{const d=lookup.get(s.section+'|'+t.id),b=el('button',d.count||'·',el('td',undefined,tr));b.style.background=d.count?heat(d.count):'#f6f8f6';b.style.color=d.count>max*.55?'white':'#173e35';b.setAttribute('aria-label',`${s.section}; ${t.name}; ${d.count} passages`);b.onmousemove=e=>tooltip(e,`${s.section}\n${t.name}: ${d.count} passages`);b.onmouseleave=hideTip;b.onclick=()=>{cell=cell&&cell.section===s.section&&cell.cluster===t.id?null:d;update();};cells.push({b,d});});});
function matches(d){const q=$('search').value.trim().toLowerCase(),s=$('section-filter').value,t=$('topic-filter').value;return(!q||d.text.toLowerCase().includes(q))&&(!s||d.section===s)&&(t===''||d.cluster===+t)&&(!cell||(d.section===cell.section&&d.cluster===cell.cluster));}
function update(){const count=rows.filter(matches).length;points.attr('opacity',d=>matches(d)?.85:.055).attr('stroke',d=>selected===d||neighbors.has(d.passage_id)?'#111':'#fff').attr('stroke-width',d=>selected===d?2.5:neighbors.has(d.passage_id)?1.8:.35).attr('stroke-dasharray',d=>neighbors.has(d.passage_id)?'2 1':null).attr('vector-effect','non-scaling-stroke');points.filter(d=>neighbors.has(d.passage_id)||selected===d).raise();cells.forEach(({b,d})=>{const active=!!cell&&cell.section===d.section&&cell.cluster===d.cluster;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));b.classList.toggle('selected',!!selected&&selected.section===d.section&&selected.cluster===d.cluster);});$('match-status').textContent=`${count} / ${rows.length} passages highlighted${cell?' · '+short(cell.section)+' × '+cell.cluster_name:''}${count?'':' · No matches; clear search or selection.'}`;}
function select(d){selected=d;neighbors=new Set(data.neighbors[d.passage_id].map(n=>n.id));hideTip();const panel=$('details');panel.replaceChildren();el('h3',`${d.passage_id} · ${d.cluster_name}`,panel);const grid=el('div',undefined,panel,'detail-grid'),left=el('div',undefined,grid);el('p',`${d.chapter} → ${d.section}${d.subsection?' → '+d.subsection:''}`,left,'metadata');el('p',`Printed page ${d.page}${d.page_end!==d.page?'–'+d.page_end:''} · PDF page ${d.pdf_page} · ${d.word_count} words`,left,'metadata');el('p',d.text,left,'passage-text');const right=el('div',undefined,grid);el('h3','Five nearest semantic passages',right);el('p','Cosine similarity in original embeddings. Neighbors use the full corpus; filters may dim their map points.',right,'hint');const ol=el('ol',undefined,right,'neighbors');data.neighbors[d.passage_id].forEach(n=>{const other=byId.get(n.id),li=el('li',undefined,ol),b=el('button',`${other.passage_id} · ${short(other.section)} · p. ${other.page} · cosine ${n.similarity.toFixed(3)}`,li);b.onclick=()=>select(other);el('p',other.text,li);});update();}
['search','section-filter','topic-filter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',update));$('reset').onclick=()=>{$('search').value='';$('section-filter').value='';$('topic-filter').value='';cell=null;selected=null;neighbors.clear();$('details').replaceChildren();el('h3','Passage details',$('details'));el('p','Select a point to read its passage and five nearest semantic neighbors.',$('details'));svg.call(zoom.transform,d3.zoomIdentity);update();};
function finding(title,text){const div=el('article',undefined,$('findings'),'finding');el('h3',title,div);el('p',text,div);return div;}
finding('1. What are the major semantic topics?',[...data.topics].sort((a,b)=>b.count-a.count).map(t=>`${t.name}: ${t.count} (${(100*t.count/rows.length).toFixed(1)}%)`).join('; ')+'. These are interpretive labels, not official categories.');
const spread=data.topics.map(t=>({...t,coverage:new Set(rows.filter(r=>r.cluster===t.id).map(r=>r.section)).size})).sort((a,b)=>b.coverage-a.coverage);const f2=finding('2. Which topics span formal sections?',spread.slice(0,3).map(t=>`${t.name} occurs in ${t.coverage} sections`).join('; ')+'. A semantic topic can cross the bulletin’s organizational boundaries.');el('button','Highlight the most widespread topic',f2).onclick=()=>{$('reset').click();$('topic-filter').value=spread[0].id;update();$('map').scrollIntoView({behavior:'smooth',block:'center'});};
const diverse=data.sections.filter(s=>s.count>=10).sort((a,b)=>b.entropy-a.entropy);finding('3. Which sections are semantically diverse?',diverse.slice(0,3).map(s=>`${short(s.section)}: ${s.entropy.toFixed(2)} bits (${s.count} passages)`).join('; ')+'. Shannon entropy measures how evenly passages occupy eight topics (maximum 3 bits). Only sections with at least ten passages are compared.');
const pair=data.cross_section_pairs.find(p=>p.similarity<.98&&byId.get(p.a).chapter!==byId.get(p.b).chapter)||data.cross_section_pairs[0],a=byId.get(pair.a),b=byId.get(pair.b),f4=finding('4. Which passages connect different sections?',`${a.passage_id} (${short(a.section)}, p. ${a.page}) and ${b.passage_id} (${short(b.section)}, p. ${b.page}) have cosine similarity ${pair.similarity.toFixed(3)}. Both describe the aims and assignments of two-credit writing courses: writing practice, weekly assignments, citations, and evaluating references. This repeated guidance links degree requirements to the procedures chapter.`);[a,b].forEach(r=>{el('button',`Read ${r.passage_id}`,f4).onclick=()=>{select(r);$('details').scrollIntoView({behavior:'smooth',block:'start'});};});
update();
}
